export const FETCHING_MINING_MONTHS = 'FETCHING_MINING_MONTHS'
export const FETCHED_MINING_MONTHS = 'FETCHED_MINING_MONTHS'
export const SAVING_MINING_MONTH = 'SAVING_MINING_MONTH'
export const SAVED_MINING_MONTH = 'SAVED_MINING_MONTH'
