export interface App {
  category: string;
  blockchain: string;
  storageNetwork: string;
  authentication: string;
  imgixImageUrl: string | null;
  id: number;
  name: string;
  categoryID: number;
  website: string;
  blockchainID: number;
  storageNetworkID: number;
  authenticationID: number;
  openSourceUrl: string;
  registrationIsOpen: boolean;
  trackingIsBlocked: boolean | null;
  description: string;
  twitterHandle: string;
  gcsImagePath: string | null;
  isKYCVerified: boolean | null;
  BTCAddress: string | null;
  contactEmail: string | null;
  submitterName: string | null;
  referralSource: string | null;
  isSubmittingOwnApp: boolean;
  productionId: number;
  referralCode: string | null;
  refSource: string | null;
  stacksAddress: string | null;
  hasCollectedKYC: null;
  hasAcceptedSECTerms: null;
  hasAcceptedTerms: null;
  accessToken: string;
  eversignDocumentID: string | null;
  jumioTransactionID: string | null;
  jumioEmbedURL: string | null;
  adminBlockstackID: string;
  imageUrl: string | null;
  createdAt: string;
  updatedAt: string;
}
